display_on_mobile:
  type: bool
  default: true
sticky_under_header:
  type: bool
  default: false
show_in_admin:
  type: bool
  default: true
svg_icons:
  type: list
  list_type: compact
  default: arrow-left|house
first_level_label:
  type: string
  default: ""
first_level_url:
  type: string
  default: ""
home_icon:
  type: string
  default: house
home_label:
  type: string
  default: "Home"
home_url:
  type: string
  default: "/"
show_topic_title:
  type: bool
  default: false
